### PR TITLE
Posterior samples

### PR DESCRIPTION
**Pull request by pberkes**
Implementation of the plot showing samples from the posterior over psychometric functions discussed in #191

### CODE REVIEW

**Review by otizonaizit — COMMENTED** [review]
In terms of code I like the PR. I don't feel into the matter enough to judge if this is indeed addressing #191 . Or better: this is clearly addressing it, but what are @LynnSchmittwilken, @guillermoaguilar and @FelixWichmann thinking about it? Is this the kind of plot you would want to see? Is the example in the documentation clear enough?

**Comment by pberkes** [comment]
To save everyone from compiling the documentation, this is what the new paragraph and plot look like

image

**Comment by FelixWichmann** [comment]
Great -- looks good and correctly shows the uncertainty.

Minor point: Leave out "optimal" in the text, simply "… around the point estimate of psychometric function."

Thank you all so much for creating this great Python version!

Cheers, Felix

**Comment by pberkes** [comment]
Docs and docstrings amended -- the point estimate of the psychometric function is no longer optimal (and has never been)

**Comment by FelixWichmann** [comment]
> Docs and docstrings amended -- the point estimate of the psychometric function is no longer optimal (and has never been)
:-)

**Comment by guillermoaguilar** [comment]
Very cool!!

**Review by guillermoaguilar — APPROVED** [review]
LGTM

**Pull request merged**
