### PR TITLE
Add a docs page for the get_standard_parameters method.

### PR DESCRIPTION
**Pull request by lschwetlick**
I tried to describe the function as best I knew how. Should we have a more in depth demonstration and tutorial, or do you think this is fine?

### CODE REVIEW

**Comment by pberkes** [comment]
LGTM! there's an error with building the docs to fix

**Comment by pberkes** [comment]
two errors actually: 1) `res` does not exist in the first cell; 2) it is called `result` in the second cell

**Comment by lschwetlick** [comment]
eh, yes. So the thing is that in this case the code cells just shouldnt be executed. Fixed it!

**Comment by lschwetlick** [comment]
Ready to merge from my side then.

**Comment by pberkes** [comment]
thanks

**Pull request merged**
