### PR TITLE
fixes threshold method, order of variables gamma and lambda was reversed

### PR DESCRIPTION
**Pull request by guillermoaguilar**

### CODE REVIEW

**Review by pberkes — CHANGES_REQUESTED** [review]
The parameters were clearly swapped, so this is a fix.

I'm concerned about the fact this:
- the test was passing before, how was that possible?
- the new test uses `unscaled=True`, which sets gamma and lambda to 0, and therefore does not test the fix

**Comment by pberkes** [comment]
BTW, the new test also passes with the old version of the code. We need to have a test that fails with the old version

**Comment by pberkes** [comment]
it's because `result.slope_at_proportion_correct` does the same as we manually do in the test, so we are not actually testing anything

**Comment by guillermoaguilar** [comment]
yeah I just fixed the test by adding unscale=True, but I don't understand what was the logic of the test in the first place....

**Comment by guillermoaguilar** [comment]
asking for help because I'm lost with that test

**Comment by pberkes** [comment]
I can have a look later, if it failed after it was fixed, it might mean that there is a similar error somewhere else

**Review by pberkes — APPROVED** [review]

**Comment by pberkes** [comment]
Hi Guillermo, I improved the previous test, and added one test that would have failed with gamma and lambda switched. See you like it

**Review by guillermoaguilar — COMMENTED** [review]
it looks good to me now. The test makes sense now

**Pull request merged**
