### PR TITLE
Move tests and demos out of `psignifit` package

### LINKED ISSUE #128: conftest.py should be in `tests` folder
otherwise tests cannot be run in the installed package

### PR DESCRIPTION
**Pull request by pberkes**
Fix #128

### CODE REVIEW

**Comment by lschwetlick** [comment]
@guillermoaguilar I guess we will need to make sure to adjust the docs accordingly, because we are compiling those demos into the docs.

**Comment by otizonaizit** [comment]
> @guillermoaguilar I guess we will need to make sure to adjust the docs accordingly, because we are compiling those demos into the docs.

well, as far as I understood from the discussion in #181 , those notebooks are jut waiting to be migrated into the new documentation created with jupyter-book, so they will be gone soon anyway. Otherwise the PR looks good to me!

**Comment by guillermoaguilar** [comment]
> well, as far as I understood from the discussion in #181 , those notebooks are jut waiting to be migrated into the new documentation created with jupyter-book, so they will be gone soon anyway. Otherwise the PR looks good to me!

YES!

**Comment by pberkes** [comment]
I had to juggle a little because github was stopping me from merging, reporting a merge conflict that was not present when merging on the command line... anyway, now I merged manually and it looks alright

**Pull request merged**
